id: D0EB1B1FE
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-03-23T11:06:07+00:00'
last_modified: '2022-05-30T07:55:55.106203+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/a7eec5e12ddce18d0ed1dbb732a42cf48f94dd09/openpecha/formatters/hfml.py
source_metadata:
  base:
    '7407':
      image_group_id: I1PD95959
      title: མོ་རྩིས་འཇམ་པའི་དབྱངས།
      total_pages: 1872
      order: 114
      base_file: 7407.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
