id: P406162AE
initial_creation_type: ocr
source_metadata:
  volumes:
    9a41c01d13a54977a433d9105fe4c83d:
      base_file: v114.txt
      image_group_id: I1PD95959
      title: མོ་རྩིས་འཇམ་པའི་དབྱངས།
      total_pages: 1872
      volume_number: 114
